
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmAssistirJogo.java
 *
 * Created on 27/07/2014, 17:40:21
 */
/**
 *
 * @author gkaustchr
 */
public class frmAssistirJogo extends javax.swing.JFrame {
    Timer timer;
    AssistirJogo jogo;
    int vencedor;

    /** Creates new form frmAssistirJogo */
    public frmAssistirJogo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void iniciarJogo() {
        
        reminder(3);
        
        lblMensagens.setText("Jogo iniciado");       
        
    }
       
    public void fechar() {
        this.dispose();
    }
    
    public void reminder(int seconds) {
        timer = new Timer();
        timer.schedule(new RemindTask(), seconds*1000);
    }

    class RemindTask extends TimerTask {
        public void run() {
  
            atualizarTela();
            
            try {
                lblTurno.setText("Jogador " + String.valueOf(jogo.turno()));
            } catch (IOException ex) {
                Logger.getLogger(frmAssistirJogo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                vencedor = jogoAcabou();
            } catch (IOException ex) {
                Logger.getLogger(frmAssistirJogo.class.getName()).log(Level.SEVERE, null, ex);
            }
            if ( vencedor != 0 ) {
                timer.cancel();
                
                JOptionPane.showMessageDialog(null, "FIM DE JOGO: O Jogador "+ String.valueOf(vencedor) +" venceu o jogo!");
                

                try {
                    Thread.sleep(1500);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmJogo.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    jogo.fecharConexao();
                } catch (IOException ex) {
                    Logger.getLogger(frmAssistirJogo.class.getName()).log(Level.SEVERE, null, ex);
                }

                fechar();
            } else {
                reminder(3);
            }

        }

    }
    
    public void atualizarTela()  {
        String atualizacao = "999";
        
        try {
            atualizacao = jogo.atualizarTela();
        } catch (IOException ex) {
            Logger.getLogger(frmJogo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        System.out.println("TELA ATUALIZADA: '"+ atualizacao +"'");
        
        lblQtdFileira1.setText( String.valueOf( atualizacao.charAt(0) ) );
        lblQtdFileira2.setText( String.valueOf( atualizacao.charAt(1) ) );
        lblQtdFileira3.setText( String.valueOf( atualizacao.charAt(2) ) );
        
    }
    
    public void cancelTimer() {
        timer.cancel();
    }
    
    public int jogoAcabou() throws IOException {
         return jogo.jogoAcabou();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMensagens = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblQtdFileira1 = new javax.swing.JLabel();
        lblQtdFileira3 = new javax.swing.JLabel();
        lblQtdFileira2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jogo do NIM - Assistir um jogo");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24));
        jLabel1.setText("IP do Servidor");

        txtIp.setFont(new java.awt.Font("Ubuntu", 0, 24));
        txtIp.setText("192.168.26.129");

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 24));
        jButton1.setText("Conectar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblStatus.setText("Status");

        jLabel4.setText("Turno:");

        jLabel2.setText("Fileira 1");

        lblTurno.setText("Status_turno");

        jLabel3.setText("Fileira 2");

        lblMensagens.setText("Mensagens");

        jLabel5.setText("Fileira 3");

        lblQtdFileira1.setText("9");

        lblQtdFileira3.setText("9");

        lblQtdFileira2.setText("9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblQtdFileira3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblQtdFileira2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblQtdFileira1))))
                            .addComponent(lblMensagens)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTurno)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStatus)
                .addGap(26, 26, 26)
                .addComponent(lblMensagens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblQtdFileira1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblQtdFileira2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblQtdFileira3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTurno))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Botão Conectar
 
        lblStatus.setText("Status: Conectando ao Servidor ...");
        
        jogo = new AssistirJogo( txtIp.getText() );
        jogo.start();
        //Thread t_jogo = jogo;
        //t_jogo.start();
        
        vencedor = 0;
        
        reminder(3);
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAssistirJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAssistirJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAssistirJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAssistirJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmAssistirJogo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMensagens;
    private javax.swing.JLabel lblQtdFileira1;
    private javax.swing.JLabel lblQtdFileira2;
    private javax.swing.JLabel lblQtdFileira3;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTextField txtIp;
    // End of variables declaration//GEN-END:variables
}
